# Файл docker-compose.yml

# Перечень volume
volumes:
  pg_data_production:
  static_voiume:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    image: sednevsergey/taski_backend
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static_voiume:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    image: sednevsergey/taski_frontend
    env_file: .env
    volumes:
      - static_voiume:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    image: sednevsergey/taski_gateway
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static_voiume:/staticfiles
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    ports:
      - 8000:80
    depends_on:
      - backend